version: '3.9'

services:
  backend:
    build: ./server
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
      - upload:/upload
    environment:
      DATABASE_CONNECTION: mongodb://db:27017/grap
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

  db:
    image: mongo:6.0
    ports:
      - 2757:27017
    restart: unless-stopped
    volumes:
      - phone:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword

  web:
    build: ./admin
    ports:
      - 3022:80
    restart: unless-stopped
    volumes:
      - ./admin:/app
      - /app/node_modules
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: 'true'

  web1:
    build: ./graborders
    ports:
      - 3015:80
    restart: unless-stopped
    volumes:
      - ./graborders:/app
      - /app/node_modules
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: 'true'

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  phone:
  upload:
